basePath: /
consumes:
- application/json
definitions:
  Task:
    description: Task defines the structure for an API Task
    properties:
      creation_time:
        description: The creation time of the task
        maxLength: 100
        type: string
        x-go-name: CreationTime
      file_uuid:
        description: The UUID of the file that is requested to be processed
        maxLength: 100
        type: string
        x-go-name: FileUUID
      id:
        description: The id of the task
        minimum: 1
        type: string
        x-go-name: ID
      result:
        description: The results contains the UUIDs that are in the file that was
          processed
        items:
          type: string
        type: array
        x-go-name: Result
      status:
        $ref: '#/definitions/TaskStatus'
    required:
    - file_uuid
    type: object
    x-go-package: github.com/nicuf/file-processor-api/task
  TaskStatus:
    description: TaskStatus is the status of a Task
    type: string
    x-go-package: github.com/nicuf/file-processor-api/task
info:
  description: Documentation for File Processor API
  title: Classification of File Processor API
  version: 1.0.0
paths:
  /files/{uuid}:
    get:
      description: Returns a list of files with UUID
      operationId: searchFiles
      responses:
        "200":
          $ref: '#/responses/searchFilesResponse'
      tags:
      - file-processor
      - ""
  /isloop/{uuid}:
    get:
      description: Returns true or false
      operationId: isLoop
      responses:
        "200":
          $ref: '#/responses/isLoopResponse'
      tags:
      - file-processor
  /task/{uuid}:
    get:
      description: Returns task info
      operationId: task
      responses:
        "200":
          $ref: '#/responses/taskInfoResponse'
      tags:
      - file-processor
    post:
      description: Add a task to be processed
      operationId: task
      responses:
        "200":
          $ref: '#/responses/taskInfoResponse'
      tags:
      - file-processor
produces:
- application/json
responses:
  isLoopResponse:
    description: True or False
  searchFilesResponse:
    description: Array of files that contains a specific UUID
    schema:
      items:
        type: string
      type: array
  taskInfoResponse:
    description: Task info
    schema:
      $ref: '#/definitions/Task'
schemes:
- http
swagger: "2.0"
